server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-admin-password: test
        web-allow-others: true